name: backup_restore_books
description: A HiveDB sample project that demonstrates backup & restore functionality.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive:
  hive_flutter:
    git:
      url: git://github.com/hivedb/hive.git
      path: hive_flutter
  path_provider: ^1.6.11
  file_picker: ^1.12.0

  cupertino_icons: ^0.1.3

flutter:
  uses-material-design: true
